language: rust
os: osx
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - ./create_dmg.sh
  - cargo build --verbose
  - RUST_LOG=dmg=info cargo test --verbose -- --test-threads 1
